import { defineConfig } from "oxlint"

export default defineConfig({
  categories: {
    correctness: "error",
    perf: "error",
    suspicious: "error",
  },
  env: {
    browser: true,
    builtin: true,
    es2024: true,
    node: true,
  },
  ignorePatterns: ["sandbox/", "scripts/", "meta.json"],
  jsPlugins: [
    "eslint-plugin-better-tailwindcss",
    "eslint-plugin-no-only-tests",
    "eslint-plugin-perfectionist",
    "eslint-plugin-unused-imports",
  ],
  overrides: [
    {
      // TypeScript compiler handles these checks
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-with": "off",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
    {
      // Webview uses Preact (lowercase DOM attrs) and custom @theme inline vars
      files: ["src/webview/**"],
      rules: {
        "better-tailwindcss/no-unknown-classes": "off",
        "react/no-unknown-property": "off",
        "react/react-in-jsx-scope": "off",
      },
    },
    {
      // Tests use JSX without explicit React/Preact import.
      // EventEmitter is from the VS Code API mock, not Node.js.
      files: ["test/**"],
      rules: {
        "react/react-in-jsx-scope": "off",
        "unicorn/prefer-event-target": "off",
      },
    },
    {
      // E2E tests require namespace imports for CJS modules (assert, vscode)
      files: ["test/vscode-e2e/**"],
      rules: {
        "import-x/no-namespace": "off",
      },
    },
  ],
  plugins: ["typescript", "import", "react", "unicorn"],
  rules: {
    // ── TypeScript ───────────────────────────────────────────────────
    "@typescript-eslint/array-type": ["error", { default: "array" }],
    "@typescript-eslint/ban-ts-comment": "error",
    "@typescript-eslint/ban-tslint-comment": "error",
    "@typescript-eslint/consistent-indexed-object-style": "error",
    "@typescript-eslint/consistent-type-definitions": "error",
    "@typescript-eslint/no-confusing-non-null-assertion": "error",
    "@typescript-eslint/no-duplicate-enum-values": "error",
    "@typescript-eslint/no-dynamic-delete": "error",
    "@typescript-eslint/no-empty-interface": "error",
    "@typescript-eslint/no-empty-object-type": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-extra-non-null-assertion": "error",
    "@typescript-eslint/no-extraneous-class": "error",
    "@typescript-eslint/no-misused-new": "error",
    "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-require-imports": "error",
    "@typescript-eslint/no-this-alias": "error",
    "@typescript-eslint/no-unnecessary-type-constraint": "error",
    "@typescript-eslint/no-unsafe-declaration-merging": "error",
    "@typescript-eslint/no-unsafe-function-type": "error",
    "@typescript-eslint/no-useless-empty-export": "error",
    "@typescript-eslint/no-wrapper-object-types": "error",
    "@typescript-eslint/prefer-as-const": "error",
    "@typescript-eslint/prefer-for-of": "error",
    "@typescript-eslint/prefer-function-type": "error",
    "@typescript-eslint/prefer-namespace-keyword": "error",
    "@typescript-eslint/prefer-ts-expect-error": "error",
    "@typescript-eslint/triple-slash-reference": "error",

    // ── Category overrides (disable unhelpful rules from categories) ─
    "import-x/no-unassigned-import": "off",
    "no-negated-condition": "off",
    "no-unused-vars": "off",
    "react/no-array-index-key": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/require-post-message-target-origin": "off",

    // ── Core ─────────────────────────────────────────────────────────
    curly: "error",
    eqeqeq: "error",
    "guard-for-in": "error",
    "no-bitwise": "error",
    "no-caller": "error",
    "no-console": "error",
    "no-eval": "error",
    "no-implied-eval": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-lone-blocks": "error",
    "no-multi-str": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-proto": "error",
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-throw-literal": "error",
    "no-unneeded-ternary": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-var": "error",
    "no-void": "error",
    "no-warning-comments": ["error", { terms: ["@nocommit"] }],
    "object-shorthand": "error",
    "operator-assignment": "error",
    "prefer-const": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    radix: "error",
    "symbol-description": "error",
    yoda: "error",

    // ── React ────────────────────────────────────────────────────────
    "react/button-has-type": "error",
    "react/checked-requires-onchange-or-readonly": "error",
    "react/iframe-missing-sandbox": "error",
    "react/jsx-boolean-value": "error",
    "react/jsx-curly-brace-presence": "error",
    "react/jsx-no-useless-fragment": "error",
    "react/prefer-es6-class": "error",
    "react/self-closing-comp": "error",
    "react/void-dom-elements-no-children": "error",

    // ── Unicorn ──────────────────────────────────────────────────────
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-lonely-if": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-static-only-class": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-this-assignment": "error",
    "unicorn/no-typeof-undefined": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-unreadable-iife": "error",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/no-useless-length-check": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-switch-case": "error",
    "unicorn/numeric-separators-style": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-code-point": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-event-target": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-math-min-max": "error",
    "unicorn/prefer-math-trunc": "error",
    "unicorn/prefer-modern-math-api": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-prototype-methods": "error",
    "unicorn/prefer-reflect-apply": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-top-level-await": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",

    // ── Import ───────────────────────────────────────────────────────
    "import-x/export": "error",
    "import-x/no-namespace": "error",

    // ── Perfectionist ────────────────────────────────────────────────
    "perfectionist/sort-enums": ["error", { partitionByComment: true, sortByValue: "always" }],
    "perfectionist/sort-heritage-clauses": "error",
    "perfectionist/sort-imports": "error",
    "perfectionist/sort-interfaces": "error",
    "perfectionist/sort-intersection-types": "error",
    "perfectionist/sort-jsx-props": "error",
    "perfectionist/sort-object-types": "error",
    "perfectionist/sort-objects": ["error", { partitionByComment: true }],
    "perfectionist/sort-union-types": "error",

    // ── Unused imports ───────────────────────────────────────────────
    "unused-imports/no-unused-imports": "error",

    // ── Tailwind ─────────────────────────────────────────────────────
    "better-tailwindcss/no-conflicting-classes": "error",
    "better-tailwindcss/no-unknown-classes": "error",
  },
})
