import { defineConfig } from "oxlint"

export default defineConfig({
  categories: {
    correctness: "off",
  },
  env: {
    browser: true,
    builtin: true,
    es2024: true,
    node: true,
  },
  jsPlugins: [
    "eslint-plugin-better-tailwindcss",
    "eslint-plugin-no-only-tests",
    "eslint-plugin-perfectionist",
    "eslint-plugin-unused-imports",
  ],
  overrides: [
    {
      // TypeScript compiler handles these checks
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-undef": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-with": "off",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
    {
      // Allow console in server-side code and scripts
      files: [
        "apps/web/app/lib/**/*.ts",
        "apps/web/server/**/*.ts",
        "apps/desktop/src/main/**/*.ts",
        "packages/shared/scripts/**/*.ts",
        "infra/scripts/**",
      ],
      rules: {
        "no-console": "off",
      },
    },
    {
      // Tailwind config uses numeric color scales (50, 100, ...) — not alphabetical
      files: ["**/tailwind/**", "**/tailwind.config.*"],
      rules: {
        "perfectionist/sort-objects": "off",
      },
    },
  ],
  plugins: ["typescript", "import", "react", "unicorn"],
  rules: {
    // TypeScript
    "@typescript-eslint/array-type": ["error", { default: "generic" }],
    "@typescript-eslint/no-duplicate-enum-values": "error",
    "@typescript-eslint/no-empty-object-type": "error",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-extra-non-null-assertion": "error",
    "@typescript-eslint/no-misused-new": "error",
    "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
    "@typescript-eslint/no-require-imports": "error",
    "@typescript-eslint/no-unnecessary-type-constraint": "error",
    "@typescript-eslint/no-unsafe-declaration-merging": "error",
    "@typescript-eslint/no-unsafe-function-type": "error",
    "@typescript-eslint/no-wrapper-object-types": "error",
    "@typescript-eslint/prefer-as-const": "error",
    "@typescript-eslint/prefer-namespace-keyword": "error",
    "@typescript-eslint/triple-slash-reference": "error",

    // Core
    "constructor-super": "error",
    curly: "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-array-constructor": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-console": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-only-tests/no-only-tests": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-undef": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-expressions": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-useless-rename": "error",
    "no-var": "error",
    "no-warning-comments": ["error", { terms: ["@nocommit"] }],
    "no-with": "error",
    "prefer-const": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",

    // React
    "react-hooks/exhaustive-deps": "error",
    "react-hooks/rules-of-hooks": "error",
    "react/display-name": "error",
    "react/jsx-key": "error",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-no-undef": "error",
    "react/no-children-prop": "error",
    "react/no-danger-with-children": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-find-dom-node": "error",
    "react/no-is-mounted": "error",
    "react/no-render-return-value": "error",
    "react/no-string-refs": "error",
    "react/no-unescaped-entities": "error",
    "react/no-unknown-property": "error",
    "react/require-render-return": "error",

    // Unicorn
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-typeof-undefined": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/numeric-separators-style": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-top-level-await": "error",
    "unicorn/text-encoding-identifier-case": "error",

    // Import
    "import-x/export": "error",
    "import-x/no-namespace": "error",

    // Perfectionist
    "perfectionist/sort-enums": ["error", { partitionByComment: true, sortByValue: "always" }],
    "perfectionist/sort-heritage-clauses": "error",
    "perfectionist/sort-imports": "error",
    "perfectionist/sort-interfaces": "error",
    "perfectionist/sort-intersection-types": "error",
    "perfectionist/sort-jsx-props": "error",
    "perfectionist/sort-object-types": "error",
    "perfectionist/sort-objects": ["error", { partitionByComment: true }],
    "perfectionist/sort-union-types": "error",

    // Unused imports
    "unused-imports/no-unused-imports": "error",

    // Tailwind
    "better-tailwindcss/no-conflicting-classes": "error",
    "better-tailwindcss/no-unknown-classes": "error",
  },
})
